### ISSUE TITLE
ajax in get response

### ISSUE THREAD

**Issue by bcmdevteam** [mizuka-wu/vue2-typeahead#21]
Hey

I found your plugin very helpful
Currently i am building api so for every request i am checking API key which i am sending in headers.
So how can i send custom header in request here, or how i can call url manually so i can set headers.

Thanks

**Comment by mizuka-wu** [comment]
bind fetch property on plugon

发自我的 iPhone

在 2018年9月21日，下午3:09，Brand Catalyst Media <notifications@github.com<mailto:notifications@github.com>> 写道：


Hey

I found your plugin very helpful
Currently i am building api so for every request i am checking API key which i am sending in headers.
So how can i send custom header in request here, or how i can call url manually so i can set headers.

Thanks

**Comment by bcmdevteam** [comment]
Also one more thing 
I want to show users search history on first tap,
but couldn't find event for that, can you help with that
